apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_dpdk_a",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "1572"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["eno1"]
                }
            },
            {
                "resourceName": "sriov_dpdk_b",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "1572"],
                    "drivers": ["vfio-pci"],
                    "pfNames": ["eno2"]
                }
            }

        ]
    }

